### ISSUE TITLE
Use termcolor

### ISSUE THREAD

**Issue by SuperFola** [Mesabloo/snowstar#1]
Instead of using raw magic codes to change the text color in a terminal, mind using termcolor.

What you are doing : https://github.com/Mesabloo/snowstar/blob/master/VM/Main/main.cpp#L10

What you should be using : https://github.com/ikalnytskyi/termcolor

**Comment by Mesabloo** [comment]
Checked it. Sounds good.
In the end, it does the same thing as I do, but with much more compatibility over different platforms.
Thanks for the review, will add it.

**Comment by Mesabloo** [comment]
@SuperFola Everything has been updated. Thanks again. Issue closed.
